#!/usr/bin/env bash
#  ____ _____ ___  ____
# |  _ \_   _/ _ \/ ___|   Derek Taylor (DistroTube)
# | | | || || | | \___ \   http://www.youtube.com/c/DistroTube
# | |_| || || |_| |___) |  http://www.gitlab.com/dtos/dtos
# |____/ |_| \___/|____/
#
# NAME: DTOS
# DESC: DT 的 Xmonad 視窗管理員安裝腳本和設定。
# WARNING: 執行腳本時請自行承擔風險
# DEPENDENCIES: gum

if [ "$(id -u)" = 0 ]; then
    echo "##################################################################"
    echo "這個腳本＊必須不使用超級使用者身分執行＊因為它會隨時間切換"
    echo "資料夾例如 \$HOME \$USER。"
    echo "\$HOME 的超級使用者的資料夾當然是「/root」。"
    echo "當然，腳本需要超級使用者的密碼時會隨時問您。"
    echo "##################################################################"
    exit 1
fi

error() { \
    clear; printf "錯誤:\\n%s\\n" "$1" >&2; exit 1;
}

echo "################################################################"
echo "##          重新整理軟體源並且正在安裝「gum」套件                ##"
echo "################################################################"
sudo pacman --noconfirm --needed -Syu gum || error "重新整理軟體源時失敗"

welcome() { \
    gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'這個腳本將會安裝 DTOS（DT 的作業系統）。' '不過這只是讓那些好奇寶寶試試看我安裝的套件和我的設定。' '在安裝時會問您的超級使用者密碼，' '所以請隨時盯著您的電腦。' 'DT（開發者：Derek Taylor，aka DistroTube）'
}

welcome || error "使用者取消"

speedwarning() { \
    gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'＊警告＊！' 'ParallelDownloads 選項尚未在 /etc/pacman.conf 中啟用。' '這可能導致下載速度會跟 Windows 一樣慢。確定繼續？' 
    gum confirm "正在安裝 DTOS" --affirmative="繼續" --negative="退出" || error "使用者取消"
}

distrowarning() { \
    gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'＊警告＊！' '雖然這個腳本適用' '所有基於 Arch Linux 的作業系統，' '不過有些作業系統會有和此腳本衝突的套件。' '確定繼續？'
    gum confirm "正在安裝 DTOS" --affirmative="繼續" --negative="退出" || error "使用者取消"
 
    
}

grep -qs "#ParallelDownloads" /etc/pacman.conf && speedwarning
grep -qs "ID=arch" /etc/os-release || distrowarning

localewarning() { \
    [[ -z $LANG || -z $LC_CTYPE ]] && \
    gum style \
    --foreground 212 --border-foreground 212 --border double \
    --align center --width 50 --margin "1 2" --padding "2 4" \
    '＊警告＊！' '您尚未設定您的語言環境，請確認' "$(gum style --bold --foreground 113 "/etc/local.conf") 的 LANG 和 $(gum style --bold --foreground 113 "LC_CTYPE") 變數設定正確" '（注意：語言環境應該相同）' "接下來執行 $(gum style --bold --foreground 57  "sudo locale-gen")" '重新啟動然後再次執行此腳本。' '請閱讀：https://wiki.archlinux.org/title/locale' && error "＊警告＊！您尚未設定您的語言環境，請確認 /etc/local.conf 的 LANG 和 LC_CTYPE 變數設定正確（注意：語言環境應該相同）接下來執行「sudo locale-gen」，' '重新啟動然後再次執行此腳本。請閱讀：https://wiki.archlinux.org/title/locale"

}

localewarning

lastchance() { \
    gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'＊警告＊！' '此腳本仍然為測試版本，' '請先在如 VirtualBox 的模擬器中執行。'
    gum confirm "是否繼續？" --affirmative="繼續" --negative="取消" || { clear; exit 1; }

}

lastchance || error "使用者取消"

addrepo() { \
    gum spin --spinner jump --title "增加 DTOS 的軟體源到 /etc/pacman.conf " -- grep -qxF "[dtos-core-repo]" /etc/pacman.conf ||
        ( echo " "; echo "[dtos-core-repo]"; echo "SigLevel = Required DatabaseOptional"; \
        echo "Server = https://gitlab.com/dtos/\$repo/-/raw/main/\$arch") | sudo tee -a /etc/pacman.conf
}

addrepo || error "增加 DTOS 軟體源到 /etc/pacman.conf 時發生錯誤。"

addkeyserver() { \
    gum spin --spinner minidot --title "正在增加金鑰伺服器到 /etc/pacman.d/gnupg/gpg.conf "  -- grep -qxF "keyserver.ubuntu.com:80" /etc/pacman.d/gnupg/gpg.conf || echo "keyserver hkp://keyserver.ubuntu.com:80" | sudo tee -a /etc/pacman.d/gnupg/gpg.conf && grep -qxF "keyserver.ubuntu.com:443" /etc/pacman.d/gnupg/gpg.conf || echo "keyserver hkps://keyserver.ubuntu.com:443" | sudo tee -a /etc/pacman.d/gnupg/gpg.conf
}

addkeyserver || error "在增加金鑰伺服器到 /etc/pacman.d/gnupg/gpg.conf 時出錯。"

receive_key() { \
    local _pgpkey="C71486C31555B12E"
gum spin --spinner points --title "正在下載 PGP 鑰匙 $_pgpkey"  -- sudo pacman-key --recv-key $_pgpkey && sudo pacman-key --lsign-key $_pgpkey || error "下載 PGP 鑰匙 $_pgpkey 時發生錯誤"
}

receive_key || error "下載 PGP 鑰匙 $_pgpkey 時發生錯誤"

gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'選擇您的視窗管理員。' 'xmonad、awesome，或 qtile。' '您至少則一，否則您將不會有使用者介面。' 'xmonad 為最佳選擇。' 

while true; do
    read -p "是否安裝 XMonad？（Yy/Nn）" yn
    case $yn in
        [Yy]* ) sudo pacman -Sy xmonad xmonad-contrib xmobar dtos-xmonad dtos-xmobar;
                break;;
        [Nn]* ) echo "您選擇不安裝 XMonad。";
                break;;
        * ) echo "請回答問題。";;
    esac
done

while true; do
read -p "是否安裝 Awesome？（Yy/Nn）" yn
    case $yn in
        [Yy]* ) sudo pacman -Sy awesome dtos-awesome ;
                break;;
        [Nn]* ) echo "您選擇不安裝 Awesome。";
                break;;
        * ) echo "請回答問題";;
    esac
done

while true; do
    read -p "是否安裝 Qtile？（Yy/Nn）" yn
    case $yn in
        [Yy]* ) sudo pacman -Sy qtile dtos-qtile ;
                break;;
        [Nn]* ) echo "您選擇不安裝 Qtile。" ;
                break;;
        * ) echo "請回答問題";;
    esac
done

# Let's install each package listed in the pkglist.txt file.
sudo pacman --needed --ask 4 -Sy - < pkglist.txt || error "Failed to install required packages."

gum spin --spinner line --title "正在複製 DTOS 設定檔案從 /etc/dtos 到 \$HOME "  -- ./DTcfg 

# Change all scripts in .local/bin to be executable.
find $HOME/.local/bin -type f -print0 | xargs -0 chmod 775

gum spin --spinner line --title "正在安裝 Doom Emacs。這可能需要幾分鐘。"  -- ./DoomEmacs || echo "安裝 Doom Emacs"
gum spin --spinner line --title "正在重新編譯 XMonad "  -- xmonad --recompile || echo "重新編譯 Xmonad 時失敗！"
gum spin --spinner dot --title "正在編譯 xmonadctl 腳本"  -- ghc -dynamic "$HOME"/.config/xmonad/xmonadctl.hs || echo "編譯 xmonadctl 腳本時失敗！"

echo "Set default user shell"
choice=$(gum choose "fish" "bash" "zsh")
sudo chsh $USER -s "/bin/$choice" && \
echo -e "$choice 已設為預設的 Shell。安裝後需要登出來套用設定。"
gum style \
    --foreground 212 --border-foreground 212 --border double \
    --align center --width 50 --margin "1 2" --padding "2 4" \
    "已設$(gum style --bold --foreground 113 $choice) " '為預設 shell'

# Disable the current login manager
sudo systemctl disable $(grep '/usr/s\?bin' /etc/systemd/system/display-manager.service | awk -F / '{print $NF}') || echo "無法停用目前的顯示管理器"
# Enable sddm as login manager
sudo systemctl enable sddm
gum style \
    --foreground 212 --border-foreground 212 --border double \
    --align center --width 50 --margin "1 2" --padding "2 4" \
    "已啟用 sddm 為登入管理器。"

## Make multicolor-sddm-theme the default sddm theme ##
# This is the sddm system configuration file.
[ -f "/usr/lib/sddm/sddm.conf.d/default.conf" ] && \
    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /usr/lib/sddm/sddm.conf.d/default.conf.backup && \
    sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /usr/lib/sddm/sddm.conf.d/default.conf

# This is the sddm local configuration file.
[ -f "/etc/sddm.conf" ] && \
    sudo cp /etc/sddm.conf /etc/sddm.conf.backup && \
    sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /etc/sddm.conf

# Create a local configuration file if it doesn't exist.
# Standard Arch Linux does not create this file by default.
[ ! -f "/etc/sddm.conf" ] && \
    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf || echo "Default sddm system config file is not found."

# ArcoLinux B Awesome uses this config location.
[ -f "/etc/sddm.conf.d/kde_settings.conf" ] && \
    sudo cp /etc/sddm.conf.d/kde_settings.conf /etc/sddm.conf.d/kde_settings.backup && \
    sudo sed -i 's/^Current=*.*/Current=multicolor-sddm-theme/g' /etc/sddm.conf.d/kde_settings.conf

gum style \
    --foreground 212 --border-foreground 212 --border double \
    --align center --width 50 --margin "1 2" --padding "2 4" \
    "DTOS 安裝完成！"

gum confirm "是否重新啟動？" && reboot || echo "歡迎來到 DTOS 的世界！"
